### PR TITLE
Indexing Class exercises

### PR DESCRIPTION
**Pull request by gwslingerland**
I will add indexing to all class exercises.
I will also fix any indexing errors I find along the way, which originate from the mechanics book. 
I will create a draft pull request for this in the other repository.

### CODE REVIEW

**Comment by gwslingerland** [comment]
I finished indexing the class exercises.
Some class exercises overlap on certain topics (e.g. force method). In these cases I decided to add a small description to the end of the class exercise index. I tried using a second indentation but as far as I know, this is not possible.

I also gave some class exercises multiple indices as they touched upon multiple topics.

In addition i added indexing to the exams and prerequisite tests.

**Review by Tom-van-Woudenberg — CHANGES_REQUESTED** [review]
Could you make the indexing a bit more specific for all class exercises so that they mathc other index items of the ocntent itself (and prerequisite tests and demonstrations, see later point)?
So for example:
`Cables; class exercise` --> `Cables; class exercise using differential equations and  equilibrium in a specific cross-section`
`Williot; Class exercise` --> `Displacements truss structures; class exercise using Williot`

And could you add to the prerequisite test and demonstration lessons index items with the topic first:
So for example for the first prerequisite test,
`Section forces in truss structures; prerequisite test using equilibrium
`

and for the first demonstration lesson:
`Differential equations; demonstration for bending`

**Comment by gwslingerland** [comment]
I made the indexing of the class exercises more descriptive.

**Review by Tom-van-Woudenberg — APPROVED** [review]
A few minor changes, but thanks again!

**Pull request merged**
